### ISSUE TITLE
I'm using Proxy Authentication but i get error:  Sign server did not return the x-set-tt-cookie header

### ISSUE THREAD

**Issue by hades12x1** [jwdeveloper/TikTokLiveJava#122]
I create list proxy data with ip and port.
Because proxy has authentication and i don't see field user and password config in object ProxyData. So i create new Proxy-Authorization value and add it to header.
But when i connect, i get error: "Sign server did not return the x-set-tt-cookie header" 
I don't known exactly problem, help me.
Thanks

**Comment by kohlerpop1** [comment]
This error is not actually from your proxy. We are having intermittent errors with the signing server which is returning that error shown. We are investigating the issue and looking into a fix.

**Comment by hades12x1** [comment]
Thank friend, i'm waiting

**Comment by kohlerpop1** [comment]
This should be fixed. Give it a shot and let me know!

**Comment by UsainSrht** [comment]
@kohlerpop1 I'm having the same problem. I was using 1.8.5 and upgraded to 1.9.2 but didn't fix it.
I use the project in a minecraft plugin.
Heres the full error:
```
io.github.jwdeveloper.tiktok.exceptions.TikTokSignServerException: Sign server did not return the x-set-tt-cookie header - ActionResult: {
  "success": true,
  "message": "HttpResponse Code: 503 | Sign server Error. Try again later.",
  "content": {
    "statusCode": 503,
    "request": {
      "method": "GET",
      "timeout": "Optional[PT3S]",
      "expectContinue": false,
      "uri": "https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=true&last_rtt=0&live_id=12&msToken=&referer=https%3A%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7489798953454619409&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&version_code=180800&webcast_language=en-US&webcast_sdk_version=1.3.0",
      "version": "Optional.empty",
      "headers": {
        "Accept": [
          "text/html,application/json,application/protobuf"
        ],
        "Accept-Language": [
          "en-US,en; q=0.9"
        ],
        "authority": [
          "www.tiktok.com"
        ],
        "Cache-Control": [
          "max-age=0"
        ],
        "Origin": [
          "https://www.tiktok.com"
        ],
        "Referer": [
          "https://www.tiktok.com/"
        ],
        "User-Agent": [
          "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36"
        ]
      }
    },
    "headers": {
      ":status": [
        "503"
      ],
      "access-control-allow-origin": [
        "*"
      ],
      "cf-cache-status": [
        "DYNAMIC"
      ],
      "cf-ray": [
        "92b9a2054ce22a87-IST"
      ],
      "content-length": [
        "62"
      ],
      "content-type": [
        "application/json; charset=utf-8"
      ],
      "date": [
        "Sat, 05 Apr 2025 14:11:08 GMT"
      ],
      "etag": [
        "W/\"3e-PWQFYO2m56exif79H5hZ/fJ7FO8\""
      ],
      "nel": [
        "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}"
      ],
      "ratelimit-limit": [
        "100"
      ],
      "ratelimit-policy": [
        "100;w=86400"
      ],
      "ratelimit-remaining": [
        "97"
      ],
      "ratelimit-reset": [
        "78895"
      ],
      "report-to": [
        "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v4?s=ywMSRwCidHyXljJw8bmhDR9%2B0l09B0Z2kKUXqYp3LIJx3ITD1oBbifva569BCjWIV2PwmUHDIDEmCc4jKrUdnaxeCD5uPB7Fc2YiyKwYVHzhgB7VD0AkWK7eTvxFQt9Y8lhbToPkTPc%3D\"}],\"group\":\"cf-nel\",\"max_age\":604800}"
      ],
      "server": [
        "cloudflare"
      ],
      "server-timing": [
        "cfL4;desc=\"?proto=TCP&rtt=10154&min_rtt=9938&rtt_var=2886&sent=8&recv=9&lost=0&retrans=0&sent_bytes=3710&recv_bytes=1599&delivery_rate=423982&cwnd=254&unsent_bytes=0&cid=638d3d1d475e6c09&ts=747&x=0\""
      ],
      "x-log-code": [
        "3"
      ],
      "x-log-id": [
        "6755971"
      ],
      "x-ratelimit-limit": [
        "100"
      ],
      "x-ratelimit-remaining": [
        "97"
      ],
      "x-ratelimit-reset": [
        "1743941163"
      ]
    },
    "body": [
      123,
      34,
      109,
      101,
      115,
      115,
      97,
      103,
      101,
      34,
      58,
      34,
      65,
      80,
      73,
      32,
      105,
      115,
      32,
      110,
      111,
      116,
      32,
      114,
      101,
      97,
      100,
      121,
      32,
      102,
      111,
      114,
      32,
      99,
      111,
      110,
      110,
      101,
      99,
      116,
      105,
      111,
      110,
      115,
      32,
      121,
      101,
      116,
      46,
      34,
      44,
      34,
      99,
      111,
      100,
      101,
      34,
      58,
      53,
      48,
      51,
      125
    ],
    "uri": "https://tiktok.eulerstream.com/webcast/fetch?aid=1988&app_language=en-US&app_name=tiktok_web&browser_language=en&browser_name=Mozilla&browser_online=true&browser_platform=Win32&browser_version=5.0+%28Windows+NT+10.0%3B+Win64%3B+x64%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Chrome%2F102.0.5005.63+Safari%2F537.36&client=ttlive-java&cookie_enabled=true&cursor=&device_platform=web&did_rule=3&fetch_rule=1&focus_state=true&from_page=user&history_len=4&identity=audience&internal_ext=&is_fullscreen=false&is_page_visible=true&last_rtt=0&live_id=12&msToken=&referer=https%3A%2F%2Fwww.tiktok.com%2F&resp_content_type=protobuf&room_id=7489798953454619409&root_referer=https%3A%2F%2Fwww.tiktok.com%2F&screen_height=1152&screen_width=2048&tz_name=Europe%2FBerlin&update_version_code=1.3.0&version_code=180800&webcast_language=en-US&webcast_sdk_version=1.3.0",
    "version": "HTTP_2"
  }
}
        at io.github.jwdeveloper.tiktok.TikTokLiveHttpClient.fetchLiveConnectionData(TikTokLiveHttpClient.java:163) ~[?:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClient.tryConnect(TikTokLiveClient.java:149) ~[?:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClient.connect(TikTokLiveClient.java:82) ~[?:?]
        at io.github.jwdeveloper.tiktok.TikTokLiveClientBuilder.buildAndConnect(TikTokLiveClientBuilder.java:184) ~[?:?]
        at me.usainsrht.sdrgfill.SDRGFill.lambda$connect$12(SDRGFill.java:283) ~[?:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.4.jar:git-Paper-497]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
